export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';

export const REMOVE_CHATS = 'REMOVE_CHATS'
export const REMOVE_USERS = 'REMOVE_USERS'

export const ADD_MESSAGE = 'ADD_MESSAGE'
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED'

export const ADD_USER = 'ADD_USER'
export const USERS_LIST = 'USERS_LIST'
export const CURRENT_USER = 'CURRENT_USER'

export const CHAT_LIST = 'CHAT_LIST'

export const REMOVE_MESSAGE = 'REMOVE_MESSAGE'
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER'

export const REMOVE_USERS_LIST = 'REMOVE_USERS_LIST'
export const REMOVE_CHAT_LIST = 'REMOVE_CHAT_LIST'